### ISSUE TITLE
#9833 - ArrayIndexOutOfBoundsException while looking for some notes

### ISSUE THREAD

**Issue by don-vip** [iandees/josm-notes#20]
From https://josm.openstreetmap.de/ticket/9833:

java.lang.ArrayIndexOutOfBoundsException: 6 >= 3
    at java.util.Vector.elementAt(Vector.java:470)
    at javax.swing.DefaultListModel.getElementAt(DefaultListModel.java:89)
    at javax.swing.JList.getSelectedValue(JList.java:2343)
    at org.openstreetmap.josm.plugins.notes.gui.NotesDialog.getSelectedNote(NotesDialog.java:410)
    at org.openstreetmap.josm.plugins.notes.NotesPlugin.updateData(NotesPlugin.java:157)
    at org.openstreetmap.josm.plugins.notes.NotesPlugin$DownloadNotesTask.run(NotesPlugin.java:308)
    at java.util.TimerThread.mainLoop(Timer.java:555)
    at java.util.TimerThread.run(Timer.java:505)

**Comment by ToeBee** [comment]
I believe this was a result of the way the plugin downloaded things. If your connection was slow it sometimes ended up having two requests running in parallel and one of them would throw this error. This is no longer a concern in the native note code since downloads work differently.
